export const ObjectSizes: Record<string, string[]> = {
  'col-12': [],
  'col-sm-11': ['md:col-11'],
  'col-sm-10': ['md:col-10'],
  'col-sm-9': ['md:col-9'],
  'col-sm-8': ['md:col-8'],
  'col-sm-7': ['md:col-7'],
  'col-sm-6': ['sm:col-6'],
  'col-sm-5': ['sm:col-6', 'md:col-5'],
  'col-md-4': ['sm:col-6', 'md:col-4'],
  'col-md-3': ['sm:col-6', 'md:col-3'],
  'w-20': ['sm:col-6', 'md:col-3', 'w-md-20'],
  'col-lg-2': ['sm:col-6', 'md:col-3', 'col-lg-2'],
  'w-14': ['sm:col-6', 'w-md-14'],
  'w-12': ['sm:col-6', 'w-md-12'],
  'w-11': ['sm:col-6', 'w-md-11'],
  'w-10': ['sm:col-6', 'w-md-10'],
  'w-9': ['sm:col-6', 'w-md-9'],
  'col-xl-1': ['sm:col-6', 'col-xl-1'],
};
