export const ObjectSizes: Record<string, string[]> = {
  'col-12': [],
  'col-sm-11': ['col-md-11'],
  'col-sm-10': ['col-md-10'],
  'col-sm-9': ['col-md-9'],
  'col-sm-8': ['col-md-8'],
  'col-sm-7': ['col-md-7'],
  'col-sm-6': ['col-sm-6'],
  'col-sm-5': ['col-sm-6', 'col-md-5'],
  'col-md-4': ['col-sm-6', 'col-md-4'],
  'col-md-3': ['col-sm-6', 'col-md-3'],
  'w-20': ['col-sm-6', 'col-md-3', 'w-md-20'],
  'col-lg-2': ['col-sm-6', 'col-md-3', 'col-lg-2'],
  'w-14': ['col-sm-6', 'w-md-14'],
  'w-12': ['col-sm-6', 'w-md-12'],
  'w-11': ['col-sm-6', 'w-md-11'],
  'w-10': ['col-sm-6', 'w-md-10'],
  'w-9': ['col-sm-6', 'w-md-9'],
  'col-xl-1': ['col-sm-6', 'col-xl-1'],
};
